### PR TITLE
Switch json library to jason

### PR DESCRIPTION
**Pull request by paulnicholson**
- Update all dependencies to their latest version
- Switch from Poison to Jason for json processing
- Use built-in specifications for travis

### CODE REVIEW

**Comment by adamkittelson** [comment]
Thanks!

**Comment by paulnicholson** [comment]
@adamkittelson Thanks for merging, can you tag and push an update to hex?

**Comment by adamkittelson** [comment]
I'm going to make a few more code updates and will likely push an update to hex next week.

**Comment by adamkittelson** [comment]
@paulnicholson pushed, thanks for the PR!

**Pull request merged**
